version: '3.9'

services:
  server:
    build: .
    ports:
      - '7000:7000'
  db:
    build: ./db/
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
